export const REGISTRATION_REQUEST = "auth/REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "auth/REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE = "auth/REGISTRATION_FAILURE";

export const LOADING_START_OR_STOP = "auth/LOADING_START_OR_STOP";

export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "auth/LOGIN_FAILURE";
