export const BRAND_CREATE_REQUEST = "brand/BRAND_CREATE_REQUEST";
export const BRAND_CREATE_SUCCESS = "brand/BRAND_CREATE_SUCCESS";
export const BRAND_CREATE_FAILURE = "brand/BRAND_CREATE_FAILURE";

export const BRAND_SAVE_REQUEST = "brand/BRAND_SAVE_REQUEST";
export const BRAND_SAVE_SUCCESS = "brand/BRAND_SAVE_SUCCESS";

export const SAVE_API_BRAND = 'brands/SAVE_API_BRAND';
export const SET_SELECTED_BRAND = 'brands/SET_SELECTED_BRAND';


export const UPDATE_BRAND_REQUEST = "brand/UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_SUCCESS = "brand/UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAILURE = "brand/UPDATE_BRAND_FAILURE";


export const DELETE_BRAND = "brand/DELETE_BRAND";
export const DELETE_BRAND_SUCCESS = "brand/DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "brand/DELETE_BRAND_FAILURE";
