export const BRANCH_CREATE_REQUEST = "branch/BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "branch/BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAILURE = "branch/BRANCH_CREATE_FAILURE";

export const UPDATE_BRANCH = "branch/UPDATE_BRANCH";
export const UPDATE_BRANCH_SUCCESS = "branch/UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAILED = "branch/UPDATE_BRANCH_FAILED";

export const DELETE_BRANCH = "branch/DELETE_BRANCH";
export const DELETE_BRANCH_SUCCESS = "branch/DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAILED = "branch/DELETE_BRANCH_FAILED";

