export const REWARD_CREATE_REQUEST = "reward/REWARD_CREATE_REQUEST";
export const REWARD_CREATE_SUCCESS = "reward/REWARD_CREATE_SUCCESS";
export const REWARD_CREATE_FAILURE = "reward/REWARD_CREATE_FAILURE";

export const UPDATE_REWARD = "reward/UPDATE_REWARD";
export const UPDATE_REWARD_SUCCESS = "reward/UPDATE_REWARD_SUCCESS";
export const UPDATE_REWARD_FAILED = "reward/UPDATE_REWARD_FAILED";

export const DELETE_REWARD = "reward/DELETE_REWARD";
export const DELETE_REWARD_SUCCESS = "reward/DELETE_REWARD_SUCCESS";
export const DELETE_REWARD_FAILED = "reward/DELETE_REWARD_FAILED";