export const TERMINAL_CREATE_REQUEST = "terminal/TERMINAL_CREATE_REQUESTQUEST";
export const TERMINAL_CREATE_SUCCESS = "terminal/TERMINAL_CREATE_SUCCESS";
export const TERMINAL_CREATE_FAILURE = "terminal/TERMINAL_CREATE_FAILURE";


export const UPDATE_TERMINAL = "terminal/UPDATE_TERMINAL";
export const UPDATE_TERMINAL_SUCCESS = "terminal/UPDATE_TERMINAL_SUCCESS";
export const UPDATE_TERMINAL_FAILED = "terminal/UPDATE_TERMINAL_FAILED";

export const DELETE_TERMINAL = "reward/DELETE_TERMINAL";
export const DELETE_TERMINAL_SUCCESS = "terminal/DELETE_TERMINAL_SUCCESS";
export const DELETE_TERMINAL_FAILED = "terminal/DELETE_TERMINAL_FAILED";